### ISSUE TITLE
[solved]Image built on ubuntu2304 failed to boot due to /dev/mmcblk2 has unsupported feature: FEATURE_C12

### ISSUE THREAD

**Issue by tz61** [dumtux/Allwinner-H616#2]
Though the image building process don't get an error, but the ext4 rootfs have some features which the kernel doesn't support.
So just use Ubuntu 22.04 to build the image.

Solution from[forums.debian.net](https://forums.debian.net/viewtopic.php?t=154055)and[www.reddit.com](https://www.reddit.com/r/debian/comments/10ze15e/comment/%5D/):
> This is a new problem. The weekly, daily, and testing versions of the debian-installler are now using a newer version of e2fstools than the version that's in the newly-installed system.
> 
> One solution: boot into an earlier version of Linux (say, from a stable Bullseye live CD/USB), and partition and format your disk. Then, boot into the new debian-installer and go through the expert install, choose manual partitioning, and continue the install without formatting the disk.

**Comment by tz61** [comment]
Maybe updating the kernel version will also solve this problem.

**Comment by dumtux** [comment]
> Though the image building process don't get an error, but the ext4 rootfs have some features which the kernel doesn't support. So just use Ubuntu 22.04 to build the image.
> 
> Solution from[forums.debian.net](https://forums.debian.net/viewtopic.php?t=154055)and[www.reddit.com](https://www.reddit.com/r/debian/comments/10ze15e/comment/%5D/):
> 
> > This is a new problem. The weekly, daily, and testing versions of the debian-installler are now using a newer version of e2fstools than the version that's in the newly-installed system.
> > One solution: boot into an earlier version of Linux (say, from a stable Bullseye live CD/USB), and partition and format your disk. Then, boot into the new debian-installer and go through the expert install, choose manual partitioning, and continue the install without formatting the disk.

Can you explain what specific features are not supported exactly?
