### ISSUE TITLE
Ubuntu 22.04?

### ISSUE THREAD

**Issue by samuk** [dumtux/Allwinner-H616#3]
Is it possible to build ubuntu 22.04 from this repo? Or does that depend on upstream work?

https://github.com/EchoHeim/Allwinner-H616/issues/6

**Comment by dumtux** [comment]
It's not possible.
I don't have a plan to support Ubuntu 22.04 or any newer version for Allwinner H616 at the moment.

**Comment by samuk** [comment]
OK thanks.
